### ISSUE TITLE
Keeping this repo up to date

### ISSUE THREAD

**Issue by asuh** [mikaelbr/node-notifier-cli#4]
Hi, came across Node Notifier and I'm glad that this CLI version exists but it seems that it's a bit out of date. Do you plan to regularly keep this updated to the latest version? Is it as easy as updating the version in `package.json`?

**Comment by piotr-cz** [comment]
Dependencies seem up to date except _node-notifier_: `^5.0.1` vs `5.1.2`
@mikaelbr are we safe to bump it's version in package.json?

**Comment by mikaelbr** [comment]
It's kind of intentionally set "low", as the version range will cause npm to install the latest version. This way the chance of the CLI and any other dependency using node-notifier using the same version of node-notifier is higher. You can see what version of node-notifier is installed by doing `npm ls node-notifier`. It will likely say `5.1.2` which is the latest.

**Comment by asuh** [comment]
Ah, that does make sense. I didn't know about the `ls` command within node to check. Thank you!
